### ISSUE TITLE
Consider bringing bash completion from SmartOS

### ISSUE THREAD

**Issue by xen0l** [OpenIndiana/openindiana-completions#1]
dladm: https://github.com/joyent/smartos-live/blob/master/overlay/generic/etc/bash/bash_completion.d/dladm
zone support for various commands (zlogin, zoneadm, zonecfg, svcs, svcadm, svcprop, pgrep, pkill, ps, ptree, wall): https://github.com/joyent/smartos-live/blob/master/overlay/generic/etc/bash/bash_completion.d/zones

**Comment by Mno-hime** [comment]
I'll have a look and incorporate, what's relevant for OI.

**Comment by alarcher** [comment]
Addressed by #4
